### ISSUE TITLE
Wrong Thai Abbreviation

### ISSUE THREAD

**Issue by PCP55** [wannaphongcom/lexicon-thai#12]
In data.csv has 2 พลอากาศเอก. The first one needs to be fixed as พลอากาศตรี

I've also gathered more Thai Abbreviation as follow. Please feel free to provide it.

```
น.ต.,นาวาอากาศตรี,ตำแหน่ง|ทหาร|ยศ|ทหารอากาศ
น.ท.,นาวาอากาศโท,ตำแหน่ง|ทหาร|ยศ|ทหารอากาศ
น.อ.,นาวาอากาศเอก,ตำแหน่ง|ทหาร|ยศ|ทหารอากาศ
ร.ต.,เรืออากาศตรี,ตำแหน่ง|ทหาร|ยศ|ทหารอากาศ
ร.ท.,เรืออากาศโท,ตำแหน่ง|ทหาร|ยศ|ทหารอากาศ
ร.อ.,เรืออากาศเอก,ตำแหน่ง|ทหาร|ยศ|ทหารอากาศ
จ.ต.,จ่าอากาศตรี,ตำแหน่ง|ทหาร|ยศ|ทหารอากาศ
จ.ท.,จ่าอากาศโท,ตำแหน่ง|ทหาร|ยศ|ทหารอากาศ
จ.อ.,จ่าอากาศเอก,ตำแหน่ง|ทหาร|ยศ|ทหารอากาศ
```

Credit: [Link](https://www.pattanakit.net/index.php?lay=show&ac=article&Id=435697&Ntype=120#:~:text=%E0%B9%80%E0%B8%A3%E0%B8%B7%E0%B8%AD%E0%B8%AD%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%A8%E0%B9%80%E0%B8%AD%E0%B8%81%20(%E0%B8%A3.%E0%B8%AD,)%20%E0%B8%AA%E0%B8%AB%E0%B8%A3%E0%B8%B1%E0%B8%90%20Second%20Lieutenant%20(2Lt))

**Comment by wannaphong** [comment]
Thank you!
